//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Cinema_Client.ServRefAddress {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Project_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressDistrictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AddressLastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressPostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address_PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.City CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Customer[] CustomersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Staff[] StaffsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Store[] StoresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressDistrict {
            get {
                return this.AddressDistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressDistrictField, value) != true)) {
                    this.AddressDistrictField = value;
                    this.RaisePropertyChanged("AddressDistrict");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressId {
            get {
                return this.AddressIdField;
            }
            set {
                if ((this.AddressIdField.Equals(value) != true)) {
                    this.AddressIdField = value;
                    this.RaisePropertyChanged("AddressId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AddressLastUpdate {
            get {
                return this.AddressLastUpdateField;
            }
            set {
                if ((this.AddressLastUpdateField.Equals(value) != true)) {
                    this.AddressLastUpdateField = value;
                    this.RaisePropertyChanged("AddressLastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressName {
            get {
                return this.AddressNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressNameField, value) != true)) {
                    this.AddressNameField = value;
                    this.RaisePropertyChanged("AddressName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressPostalCode {
            get {
                return this.AddressPostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressPostalCodeField, value) != true)) {
                    this.AddressPostalCodeField = value;
                    this.RaisePropertyChanged("AddressPostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address_Phone {
            get {
                return this.Address_PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.Address_PhoneField, value) != true)) {
                    this.Address_PhoneField = value;
                    this.RaisePropertyChanged("Address_Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.City City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Customer[] Customers {
            get {
                return this.CustomersField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomersField, value) != true)) {
                    this.CustomersField = value;
                    this.RaisePropertyChanged("Customers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Staff[] Staffs {
            get {
                return this.StaffsField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffsField, value) != true)) {
                    this.StaffsField = value;
                    this.RaisePropertyChanged("Staffs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Store[] Stores {
            get {
                return this.StoresField;
            }
            set {
                if ((object.ReferenceEquals(this.StoresField, value) != true)) {
                    this.StoresField = value;
                    this.RaisePropertyChanged("Stores");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Projet_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Address[] AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CityLastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Country CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CountryIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Address[] Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((this.CityIdField.Equals(value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CityLastUpdate {
            get {
                return this.CityLastUpdateField;
            }
            set {
                if ((this.CityLastUpdateField.Equals(value) != true)) {
                    this.CityLastUpdateField = value;
                    this.RaisePropertyChanged("CityLastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Country Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CountryId {
            get {
                return this.CountryIdField;
            }
            set {
                if ((this.CountryIdField.Equals(value) != true)) {
                    this.CountryIdField = value;
                    this.RaisePropertyChanged("CountryId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Projet_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AddressIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CustomerActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CustomerCreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CustomerLastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Payment[] PaymentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Rental[] RentalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Store StoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StoreIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AddressId {
            get {
                return this.AddressIdField;
            }
            set {
                if ((this.AddressIdField.Equals(value) != true)) {
                    this.AddressIdField = value;
                    this.RaisePropertyChanged("AddressId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CustomerActive {
            get {
                return this.CustomerActiveField;
            }
            set {
                if ((this.CustomerActiveField.Equals(value) != true)) {
                    this.CustomerActiveField = value;
                    this.RaisePropertyChanged("CustomerActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CustomerCreateDate {
            get {
                return this.CustomerCreateDateField;
            }
            set {
                if ((this.CustomerCreateDateField.Equals(value) != true)) {
                    this.CustomerCreateDateField = value;
                    this.RaisePropertyChanged("CustomerCreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerEmail {
            get {
                return this.CustomerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerEmailField, value) != true)) {
                    this.CustomerEmailField = value;
                    this.RaisePropertyChanged("CustomerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerFirstName {
            get {
                return this.CustomerFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerFirstNameField, value) != true)) {
                    this.CustomerFirstNameField = value;
                    this.RaisePropertyChanged("CustomerFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerLastName {
            get {
                return this.CustomerLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerLastNameField, value) != true)) {
                    this.CustomerLastNameField = value;
                    this.RaisePropertyChanged("CustomerLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CustomerLastUpdate {
            get {
                return this.CustomerLastUpdateField;
            }
            set {
                if ((this.CustomerLastUpdateField.Equals(value) != true)) {
                    this.CustomerLastUpdateField = value;
                    this.RaisePropertyChanged("CustomerLastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Payment[] Payments {
            get {
                return this.PaymentsField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentsField, value) != true)) {
                    this.PaymentsField = value;
                    this.RaisePropertyChanged("Payments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Rental[] Rentals {
            get {
                return this.RentalsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalsField, value) != true)) {
                    this.RentalsField = value;
                    this.RaisePropertyChanged("Rentals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Store Store {
            get {
                return this.StoreField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreField, value) != true)) {
                    this.StoreField = value;
                    this.RaisePropertyChanged("Store");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StoreId {
            get {
                return this.StoreIdField;
            }
            set {
                if ((this.StoreIdField.Equals(value) != true)) {
                    this.StoreIdField = value;
                    this.RaisePropertyChanged("StoreId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Staff", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Projet_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Staff : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AddressIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Staff[] PaymentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Rental[] RentalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StaffActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StaffIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StaffLastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] StaffPictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Store StoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StoreIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AddressId {
            get {
                return this.AddressIdField;
            }
            set {
                if ((this.AddressIdField.Equals(value) != true)) {
                    this.AddressIdField = value;
                    this.RaisePropertyChanged("AddressId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Staff[] Payments {
            get {
                return this.PaymentsField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentsField, value) != true)) {
                    this.PaymentsField = value;
                    this.RaisePropertyChanged("Payments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Rental[] Rentals {
            get {
                return this.RentalsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalsField, value) != true)) {
                    this.RentalsField = value;
                    this.RaisePropertyChanged("Rentals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StaffActive {
            get {
                return this.StaffActiveField;
            }
            set {
                if ((this.StaffActiveField.Equals(value) != true)) {
                    this.StaffActiveField = value;
                    this.RaisePropertyChanged("StaffActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffEmail {
            get {
                return this.StaffEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffEmailField, value) != true)) {
                    this.StaffEmailField = value;
                    this.RaisePropertyChanged("StaffEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffFirstName {
            get {
                return this.StaffFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffFirstNameField, value) != true)) {
                    this.StaffFirstNameField = value;
                    this.RaisePropertyChanged("StaffFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StaffId {
            get {
                return this.StaffIdField;
            }
            set {
                if ((this.StaffIdField.Equals(value) != true)) {
                    this.StaffIdField = value;
                    this.RaisePropertyChanged("StaffId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffLastName {
            get {
                return this.StaffLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffLastNameField, value) != true)) {
                    this.StaffLastNameField = value;
                    this.RaisePropertyChanged("StaffLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StaffLastUpdate {
            get {
                return this.StaffLastUpdateField;
            }
            set {
                if ((this.StaffLastUpdateField.Equals(value) != true)) {
                    this.StaffLastUpdateField = value;
                    this.RaisePropertyChanged("StaffLastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffPassword {
            get {
                return this.StaffPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffPasswordField, value) != true)) {
                    this.StaffPasswordField = value;
                    this.RaisePropertyChanged("StaffPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] StaffPicture {
            get {
                return this.StaffPictureField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffPictureField, value) != true)) {
                    this.StaffPictureField = value;
                    this.RaisePropertyChanged("StaffPicture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffUsername {
            get {
                return this.StaffUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffUsernameField, value) != true)) {
                    this.StaffUsernameField = value;
                    this.RaisePropertyChanged("StaffUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Store Store {
            get {
                return this.StoreField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreField, value) != true)) {
                    this.StoreField = value;
                    this.RaisePropertyChanged("Store");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StoreId {
            get {
                return this.StoreIdField;
            }
            set {
                if ((this.StoreIdField.Equals(value) != true)) {
                    this.StoreIdField = value;
                    this.RaisePropertyChanged("StoreId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Store", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Projet_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Store : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AdresseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Customer[] CustomersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Staff[] StaffsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Film[] StoreFilmsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StoreIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StoreLastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StoreManagerStaffIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AdresseId {
            get {
                return this.AdresseIdField;
            }
            set {
                if ((this.AdresseIdField.Equals(value) != true)) {
                    this.AdresseIdField = value;
                    this.RaisePropertyChanged("AdresseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Customer[] Customers {
            get {
                return this.CustomersField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomersField, value) != true)) {
                    this.CustomersField = value;
                    this.RaisePropertyChanged("Customers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Staff[] Staffs {
            get {
                return this.StaffsField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffsField, value) != true)) {
                    this.StaffsField = value;
                    this.RaisePropertyChanged("Staffs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Film[] StoreFilms {
            get {
                return this.StoreFilmsField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreFilmsField, value) != true)) {
                    this.StoreFilmsField = value;
                    this.RaisePropertyChanged("StoreFilms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StoreId {
            get {
                return this.StoreIdField;
            }
            set {
                if ((this.StoreIdField.Equals(value) != true)) {
                    this.StoreIdField = value;
                    this.RaisePropertyChanged("StoreId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StoreLastUpdate {
            get {
                return this.StoreLastUpdateField;
            }
            set {
                if ((this.StoreLastUpdateField.Equals(value) != true)) {
                    this.StoreLastUpdateField = value;
                    this.RaisePropertyChanged("StoreLastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StoreManagerStaffId {
            get {
                return this.StoreManagerStaffIdField;
            }
            set {
                if ((this.StoreManagerStaffIdField.Equals(value) != true)) {
                    this.StoreManagerStaffIdField = value;
                    this.RaisePropertyChanged("StoreManagerStaffId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Projet_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.City[] CitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CountryLastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.City[] Cities {
            get {
                return this.CitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.CitiesField, value) != true)) {
                    this.CitiesField = value;
                    this.RaisePropertyChanged("Cities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId {
            get {
                return this.CountryIdField;
            }
            set {
                if ((this.CountryIdField.Equals(value) != true)) {
                    this.CountryIdField = value;
                    this.RaisePropertyChanged("CountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CountryLastUpdate {
            get {
                return this.CountryLastUpdateField;
            }
            set {
                if ((this.CountryLastUpdateField.Equals(value) != true)) {
                    this.CountryLastUpdateField = value;
                    this.RaisePropertyChanged("CountryLastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Projet_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Payment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaymentAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PaymentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaymentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PaymentLastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Rental RentalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RentalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Staff StaffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StaffIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentAmount {
            get {
                return this.PaymentAmountField;
            }
            set {
                if ((this.PaymentAmountField.Equals(value) != true)) {
                    this.PaymentAmountField = value;
                    this.RaisePropertyChanged("PaymentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PaymentDate {
            get {
                return this.PaymentDateField;
            }
            set {
                if ((this.PaymentDateField.Equals(value) != true)) {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentId {
            get {
                return this.PaymentIdField;
            }
            set {
                if ((this.PaymentIdField.Equals(value) != true)) {
                    this.PaymentIdField = value;
                    this.RaisePropertyChanged("PaymentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PaymentLastUpdate {
            get {
                return this.PaymentLastUpdateField;
            }
            set {
                if ((this.PaymentLastUpdateField.Equals(value) != true)) {
                    this.PaymentLastUpdateField = value;
                    this.RaisePropertyChanged("PaymentLastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Rental Rental {
            get {
                return this.RentalField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalField, value) != true)) {
                    this.RentalField = value;
                    this.RaisePropertyChanged("Rental");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RentalId {
            get {
                return this.RentalIdField;
            }
            set {
                if ((this.RentalIdField.Equals(value) != true)) {
                    this.RentalIdField = value;
                    this.RaisePropertyChanged("RentalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Staff Staff {
            get {
                return this.StaffField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffField, value) != true)) {
                    this.StaffField = value;
                    this.RaisePropertyChanged("Staff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StaffId {
            get {
                return this.StaffIdField;
            }
            set {
                if ((this.StaffIdField.Equals(value) != true)) {
                    this.StaffIdField = value;
                    this.RaisePropertyChanged("StaffId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rental", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Projet_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Rental : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Inventory InventoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> InventoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Payment[] PaymentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RentalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RentalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RentalLastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RentalReturnDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReturnedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Staff StaffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StaffIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Inventory Inventory {
            get {
                return this.InventoryField;
            }
            set {
                if ((object.ReferenceEquals(this.InventoryField, value) != true)) {
                    this.InventoryField = value;
                    this.RaisePropertyChanged("Inventory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> InventoryId {
            get {
                return this.InventoryIdField;
            }
            set {
                if ((this.InventoryIdField.Equals(value) != true)) {
                    this.InventoryIdField = value;
                    this.RaisePropertyChanged("InventoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Payment[] Payments {
            get {
                return this.PaymentsField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentsField, value) != true)) {
                    this.PaymentsField = value;
                    this.RaisePropertyChanged("Payments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RentalDate {
            get {
                return this.RentalDateField;
            }
            set {
                if ((this.RentalDateField.Equals(value) != true)) {
                    this.RentalDateField = value;
                    this.RaisePropertyChanged("RentalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RentalId {
            get {
                return this.RentalIdField;
            }
            set {
                if ((this.RentalIdField.Equals(value) != true)) {
                    this.RentalIdField = value;
                    this.RaisePropertyChanged("RentalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RentalLastUpdate {
            get {
                return this.RentalLastUpdateField;
            }
            set {
                if ((this.RentalLastUpdateField.Equals(value) != true)) {
                    this.RentalLastUpdateField = value;
                    this.RaisePropertyChanged("RentalLastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RentalReturnDate {
            get {
                return this.RentalReturnDateField;
            }
            set {
                if ((this.RentalReturnDateField.Equals(value) != true)) {
                    this.RentalReturnDateField = value;
                    this.RaisePropertyChanged("RentalReturnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Returned {
            get {
                return this.ReturnedField;
            }
            set {
                if ((this.ReturnedField.Equals(value) != true)) {
                    this.ReturnedField = value;
                    this.RaisePropertyChanged("Returned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Staff Staff {
            get {
                return this.StaffField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffField, value) != true)) {
                    this.StaffField = value;
                    this.RaisePropertyChanged("Staff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StaffId {
            get {
                return this.StaffIdField;
            }
            set {
                if ((this.StaffIdField.Equals(value) != true)) {
                    this.StaffIdField = value;
                    this.RaisePropertyChanged("StaffId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inventory", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Projet_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Inventory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Film FilmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InventoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InventoryLastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Rental[] RentalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Store StoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Film Film {
            get {
                return this.FilmField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmField, value) != true)) {
                    this.FilmField = value;
                    this.RaisePropertyChanged("Film");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InventoryId {
            get {
                return this.InventoryIdField;
            }
            set {
                if ((this.InventoryIdField.Equals(value) != true)) {
                    this.InventoryIdField = value;
                    this.RaisePropertyChanged("InventoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InventoryLastUpdate {
            get {
                return this.InventoryLastUpdateField;
            }
            set {
                if ((this.InventoryLastUpdateField.Equals(value) != true)) {
                    this.InventoryLastUpdateField = value;
                    this.RaisePropertyChanged("InventoryLastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Rental[] Rentals {
            get {
                return this.RentalsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalsField, value) != true)) {
                    this.RentalsField = value;
                    this.RaisePropertyChanged("Rentals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Store Store {
            get {
                return this.StoreField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreField, value) != true)) {
                    this.StoreField = value;
                    this.RaisePropertyChanged("Store");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Film", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Projet_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Film : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Category[] CategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilmDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilmIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FilmLastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilmLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilmOriginalLanguageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilmRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilmReleaseYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilmRentalDurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilmRentalRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilmReplacementCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilmSpecialFeaturesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilmTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Language LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Store[] StoresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Category[] Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilmDescription {
            get {
                return this.FilmDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmDescriptionField, value) != true)) {
                    this.FilmDescriptionField = value;
                    this.RaisePropertyChanged("FilmDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FilmId {
            get {
                return this.FilmIdField;
            }
            set {
                if ((this.FilmIdField.Equals(value) != true)) {
                    this.FilmIdField = value;
                    this.RaisePropertyChanged("FilmId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FilmLastUpdate {
            get {
                return this.FilmLastUpdateField;
            }
            set {
                if ((this.FilmLastUpdateField.Equals(value) != true)) {
                    this.FilmLastUpdateField = value;
                    this.RaisePropertyChanged("FilmLastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FilmLength {
            get {
                return this.FilmLengthField;
            }
            set {
                if ((this.FilmLengthField.Equals(value) != true)) {
                    this.FilmLengthField = value;
                    this.RaisePropertyChanged("FilmLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FilmOriginalLanguageId {
            get {
                return this.FilmOriginalLanguageIdField;
            }
            set {
                if ((this.FilmOriginalLanguageIdField.Equals(value) != true)) {
                    this.FilmOriginalLanguageIdField = value;
                    this.RaisePropertyChanged("FilmOriginalLanguageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilmRate {
            get {
                return this.FilmRateField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmRateField, value) != true)) {
                    this.FilmRateField = value;
                    this.RaisePropertyChanged("FilmRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilmReleaseYear {
            get {
                return this.FilmReleaseYearField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmReleaseYearField, value) != true)) {
                    this.FilmReleaseYearField = value;
                    this.RaisePropertyChanged("FilmReleaseYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FilmRentalDuration {
            get {
                return this.FilmRentalDurationField;
            }
            set {
                if ((this.FilmRentalDurationField.Equals(value) != true)) {
                    this.FilmRentalDurationField = value;
                    this.RaisePropertyChanged("FilmRentalDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FilmRentalRate {
            get {
                return this.FilmRentalRateField;
            }
            set {
                if ((this.FilmRentalRateField.Equals(value) != true)) {
                    this.FilmRentalRateField = value;
                    this.RaisePropertyChanged("FilmRentalRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FilmReplacementCost {
            get {
                return this.FilmReplacementCostField;
            }
            set {
                if ((this.FilmReplacementCostField.Equals(value) != true)) {
                    this.FilmReplacementCostField = value;
                    this.RaisePropertyChanged("FilmReplacementCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilmSpecialFeatures {
            get {
                return this.FilmSpecialFeaturesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmSpecialFeaturesField, value) != true)) {
                    this.FilmSpecialFeaturesField = value;
                    this.RaisePropertyChanged("FilmSpecialFeatures");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilmTitle {
            get {
                return this.FilmTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmTitleField, value) != true)) {
                    this.FilmTitleField = value;
                    this.RaisePropertyChanged("FilmTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Language Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Store[] Stores {
            get {
                return this.StoresField;
            }
            set {
                if ((object.ReferenceEquals(this.StoresField, value) != true)) {
                    this.StoresField = value;
                    this.RaisePropertyChanged("Stores");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Projet_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Language : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Film[] FilmsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LanguageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LanguageLastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Film[] Films {
            get {
                return this.FilmsField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmsField, value) != true)) {
                    this.FilmsField = value;
                    this.RaisePropertyChanged("Films");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LanguageId {
            get {
                return this.LanguageIdField;
            }
            set {
                if ((this.LanguageIdField.Equals(value) != true)) {
                    this.LanguageIdField = value;
                    this.RaisePropertyChanged("LanguageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LanguageLastUpdate {
            get {
                return this.LanguageLastUpdateField;
            }
            set {
                if ((this.LanguageLastUpdateField.Equals(value) != true)) {
                    this.LanguageLastUpdateField = value;
                    this.RaisePropertyChanged("LanguageLastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageName {
            get {
                return this.LanguageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageNameField, value) != true)) {
                    this.LanguageNameField = value;
                    this.RaisePropertyChanged("LanguageName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Projet_Cinema.Model")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CategoryLastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Projet_Cinema_Client.ServRefAddress.Film[] FilmsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CategoryLastUpdate {
            get {
                return this.CategoryLastUpdateField;
            }
            set {
                if ((this.CategoryLastUpdateField.Equals(value) != true)) {
                    this.CategoryLastUpdateField = value;
                    this.RaisePropertyChanged("CategoryLastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Projet_Cinema_Client.ServRefAddress.Film[] Films {
            get {
                return this.FilmsField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmsField, value) != true)) {
                    this.FilmsField = value;
                    this.RaisePropertyChanged("Films");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServRefAddress.IAddressService")]
    public interface IAddressService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/Add", ReplyAction="http://tempuri.org/IAddressService/AddResponse")]
        Projet_Cinema_Client.ServRefAddress.Address Add(Projet_Cinema_Client.ServRefAddress.Address a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/Add", ReplyAction="http://tempuri.org/IAddressService/AddResponse")]
        System.Threading.Tasks.Task<Projet_Cinema_Client.ServRefAddress.Address> AddAsync(Projet_Cinema_Client.ServRefAddress.Address a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/get_list_address", ReplyAction="http://tempuri.org/IAddressService/get_list_addressResponse")]
        Projet_Cinema_Client.ServRefAddress.Address[] get_list_address();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/get_list_address", ReplyAction="http://tempuri.org/IAddressService/get_list_addressResponse")]
        System.Threading.Tasks.Task<Projet_Cinema_Client.ServRefAddress.Address[]> get_list_addressAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/Modify", ReplyAction="http://tempuri.org/IAddressService/ModifyResponse")]
        Projet_Cinema_Client.ServRefAddress.Address Modify(Projet_Cinema_Client.ServRefAddress.Address a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/Modify", ReplyAction="http://tempuri.org/IAddressService/ModifyResponse")]
        System.Threading.Tasks.Task<Projet_Cinema_Client.ServRefAddress.Address> ModifyAsync(Projet_Cinema_Client.ServRefAddress.Address a);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddressServiceChannel : Projet_Cinema_Client.ServRefAddress.IAddressService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddressServiceClient : System.ServiceModel.ClientBase<Projet_Cinema_Client.ServRefAddress.IAddressService>, Projet_Cinema_Client.ServRefAddress.IAddressService {
        
        public AddressServiceClient() {
        }
        
        public AddressServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddressServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Projet_Cinema_Client.ServRefAddress.Address Add(Projet_Cinema_Client.ServRefAddress.Address a) {
            return base.Channel.Add(a);
        }
        
        public System.Threading.Tasks.Task<Projet_Cinema_Client.ServRefAddress.Address> AddAsync(Projet_Cinema_Client.ServRefAddress.Address a) {
            return base.Channel.AddAsync(a);
        }
        
        public Projet_Cinema_Client.ServRefAddress.Address[] get_list_address() {
            return base.Channel.get_list_address();
        }
        
        public System.Threading.Tasks.Task<Projet_Cinema_Client.ServRefAddress.Address[]> get_list_addressAsync() {
            return base.Channel.get_list_addressAsync();
        }
        
        public Projet_Cinema_Client.ServRefAddress.Address Modify(Projet_Cinema_Client.ServRefAddress.Address a) {
            return base.Channel.Modify(a);
        }
        
        public System.Threading.Tasks.Task<Projet_Cinema_Client.ServRefAddress.Address> ModifyAsync(Projet_Cinema_Client.ServRefAddress.Address a) {
            return base.Channel.ModifyAsync(a);
        }
    }
}
